import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Tasks",
  description: "Generated by Darkhub.dev",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <header>
          <Navbar />
        </header>
        <main className="min-h-screen flex justify-center items-center mx-auto container">
        {children}
        </main>
          <Footer />
      </body>
    </html>
  );
}
